before_install: sudo apt-get install cmake

language: cpp

compiler:
  - gcc
  - clang



script: 

 - cmake ..
 - cmake build

notifications:
  recipients:
    - mdonaghey075@gmail.com
  email:
    on_success: change
    on_failure: always