before_install: sudo apt-get install cmake

language: cpp

compiler:
  - gcc
  - clang

before_script:
- make
script: 

 - make

notifications:
  recipients:
    - mdonaghey075@gmail.com
  email:
    on_success: change
    on_failure: always